---
# tasks file for common

- debug:
    var: env
      
- name: config for for all distos
  include: config.yml

- name: disto specific config
  include: config-{{ ansible_distribution }}.yml

#- name: packages for steve
#  include: packages.yml
