---
- name: standard packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - net-tools
    - bind-utils
    - epel-release

- name: update the system
  yum:
    name: "*"
    state: latest
  when: patch == true
