---
- name: add default FW rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250-10252/tcp"
    - "10255/tcp"
  notify: reload_firewall
  tags:
    - fw

- name: disabled selinux
  command: setenforce 0
  register: setenforce
  failed_when:  "'SELinux is disabled' not in setenforce.stderr"

- name: disable selinux config
  ini_file:
    path: /etc/sysconfig/selinux
    section:
    option: SELINUX
    value: disabled
    no_extra_spaces: true

- name: Enable the br_netfilter module for cluster communication
  command: modprobe br_netfilter

- name: Enable bridge-nf-call-iptables
  command: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

- name: Disable swap to prevent memory allocation issues
  command: swapoff -a

- name: Disable swap in fstab
  lineinfile:
    path: /etc/fstab
    regexp: "^/dev/mapper/centos-swap"
    line: "#/dev/mapper/centos-swap"

