---
# handlers file for ./roles/kub_node
- name: firewalld handler
  command: firewall-cmd --reload
  listen: reload_firewall

- name: configure_docker_c_group_driver
  lineinfile:
    regexp: "^ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock"
    line: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd" 
  listen: configure_docker_c_group_driver
  notify: restart_docker

- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: running
