#!/bin/bash
# ssh-multi
# D.Kovalov
# Based on http://linuxpixies.blogspot.jp/2011/06/tmux-copy-mode-and-how-to-control.html

# a script to ssh multiple servers over multiple tmux panes


starttmux() {
    if [ -z "$HOSTS" ]; then
       echo -n "Please provide of list of hosts separated by spaces [ENTER]: "
       read HOSTS
    fi

    local hosts=( $HOSTS )
    ssh_opts="StrictHostKeyChecking=no"
    tmux new-session -d "ssh $user@${hosts[0]} -o $ssh_opts 2>/dev/null"
    unset hosts[0];
    for i in "${hosts[@]}"; do
        tmux split-window -h  "ssh $user@$i -o $ssh_opts"
        tmux select-layout tiled > /dev/null
    done
    tmux select-pane -t 0
    tmux set-window-option synchronize-panes on > /dev/null

 #Command Aliases avaliable in tmux 2.4 onwards
 #   tmux set-option -s command-alias[10] sy='set synchronize-panes on'    
 #   tmux set-option -s command-alias[11] sn='set synchronize-panes off'


}

HOSTS=${HOSTS:=$*}

read -p "Username ? [$(whoami)]" user
[[ $user == "" ]] && user=$(whoami)

echo "connecting as $user"

starttmux
tmux attach
