---
# tasks file for ./roles/kub_node
- name: config for kubernetes node
  include: config-{{ ansible_distribution }}.yml
  tags: kube

- name: packages for kubernetes node
  include: packages-{{ ansible_distribution }}.yml
  tags: kube
